FROM golang:1.26 AS builder

WORKDIR /home
COPY . .
RUN go mod download && go build ./main.go

FROM openeuler/openeuler:24.03
LABEL maintainer="Zhou Yi 1123678689@qq.com"

RUN dnf install -y git wget tar gzip && \
    wget -O /usr/bin/tini https://github.com/krallin/tini/releases/download/v0.19.0/tini-amd64 && \
    chmod +x /usr/bin/tini && \
    wget https://github.com/git-lfs/git-lfs/releases/download/v3.3.0/git-lfs-linux-amd64-v3.3.0.tar.gz && \
    tar -xzf git-lfs-linux-amd64-v3.3.0.tar.gz && \
    cd git-lfs-3.3.0 && \
    ./install.sh && \
    rm -rf git-lfs-* && \
    dnf clean all

RUN useradd -s /bin/bash BigFiles
USER BigFiles
WORKDIR /home/BigFiles
COPY --chown=BigFiles:group --from=BUILDER /home/main /home/BigFiles/main
COPY --chown=BigFiles:group --from=BUILDER /home/scripts/lfsNameQuery.py /home/BigFiles/lfsNameQuery.py

EXPOSE 5000
ENTRYPOINT ["tini", "--", "/home/BigFiles/main"]